openapi: "3.0.1"
info:
  title: "SOAP-API"
  version: "2023-11-03T17:46:48Z"

paths:
  /mockendpoint:
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:xslt-transformer/invocations'
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/xml: "#set($inputRoot = $input.path('$.body'))$inputRoot"
        requestTemplates:
          application/xml: "{\n  \"body\" : $input.json('$')\n}\n"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
 
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
