version = 0.1
[default]
[default.global]
[default.global.parameters]
stack_name = "sam-app"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.sync.parameters]
watch = true

stack_name = "sam-app"
s3_prefix = "sam-app"
confirm_changeset = true
image_repositories = []
